# Generated by Django 5.2.17 on 2026-10-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_s', models.IntegerField(default=60)),
                ('grace_s', models.IntegerField(default=30)),
                ('router_grace', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('uk', 'Ukrainian'), ('en', 'English'), ('ru', 'Russian')], default='uk', max_length=2)),
                ('bot_token', models.CharField(max_length=255)),
                ('chat_id', models.BigIntegerField()),
                ('device_key', models.CharField(max_length=32, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='LocationState',
            fields=[
                ('location', models.OneToOneField(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to='powermon.location')),
                ('status', models.CharField(default='waiting', max_length=8)),
                ('state_version', models.BigIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(null=True)),
                ('on_since', models.DateTimeField(null=True)),
                ('outage_started_at', models.DateTimeField(null=True)),
                ('window_start_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'location_state',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('period_s__gte', 10), ('period_s__lte', 3600)), name='location_period_10_3600'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('grace_s__gte', 10), ('grace_s__lte', 3600)), name='location_grace_10_3600'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(('language__in', ('uk', 'en', 'ru'))), name='location_language_valid'),
        ),
        migrations.AddConstraint(
            model_name='locationstate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('waiting', 'on', 'off'))), name='location_state_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='locationstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'off'), _negated=True), ('outage_started_at__isnull', False), _connector='OR'), name='location_state_off_needs_outage_start'),
        ),
    ]
