# Generated by Django 5.2.17 on 2026-10-01 08:29
#
# Edited by hand (P-9):
# - BtreeGistExtension() is the first operation. makemigrations never adds it, and the
#   power_interval exclusion constraint needs btree_gist to compare location_id with =.
# - The last operation inserts the system_state singleton row (id 1).
# - The exclusion constraint imports powermon.engine.db.TsTzRange: never move that class.

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import powermon.engine.db
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


def create_system_state_row(apps, schema_editor):
    apps.get_model("powermon", "SystemState").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0001_initial'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('web_started_at', models.DateTimeField(null=True)),
                ('last_cycle_completed_at', models.DateTimeField(null=True)),
                ('detection_resumed_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'system_state',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='system_state_singleton')],
            },
        ),
        migrations.CreateModel(
            name='PowerInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('outage_start_at', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='powermon.location')),
            ],
            options={
                'db_table': 'power_interval',
                'indexes': [models.Index(fields=['location', 'start_at'], name='power_interval_loc_start')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ('on', 'off', 'not_monitored'))), name='power_interval_state_valid'), models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='power_interval_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('outage_start_at__isnull', False), ('state', 'off')), models.Q(models.Q(('state', 'off'), _negated=True), ('outage_start_at__isnull', True)), _connector='OR'), name='power_interval_outage_start_iff_off'), models.UniqueConstraint(condition=models.Q(('end_at__isnull', True)), fields=('location',), name='power_interval_one_open'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(powermon.engine.db.TsTzRange('start_at', 'end_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('location', '=')], name='power_interval_no_overlap')],
            },
        ),
        migrations.RunPython(create_system_state_row, migrations.RunPython.noop),
    ]
