# Generated by Django 5.2.17 on 2026-10-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0002_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=32)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(null=True)),
                ('location', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_messages', to='powermon.location')),
            ],
            options={
                'db_table': 'outbox_message',
                'indexes': [models.Index(condition=models.Q(('status__in', ('pending', 'sending'))), fields=['channel', 'location', 'id'], name='outbox_open_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('channel__in', ('subscriber', 'ops'))), name='outbox_channel_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'sending', 'sent', 'uncertain', 'expired', 'dropped'))), name='outbox_status_valid')],
            },
        ),
    ]
