# Generated by Django 5.2.17 on 2026-10-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0003_outbox_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('location', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ops_incidents', to='powermon.location')),
            ],
            options={
                'db_table': 'ops_incident',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('kind', 'location'), name='ops_incident_one_open', nulls_distinct=False)],
            },
        ),
    ]
