# Generated by Django 5.2.17 on 2026-10-02 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0004_ops_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField()),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('pinned', models.BooleanField(default=False)),
                ('pin_failed_at', models.DateTimeField(null=True)),
                ('last_rendered_at', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(null=True)),
                ('retired_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='chart_messages', to='powermon.location')),
            ],
            options={
                'db_table': 'chart_message',
                'constraints': [models.UniqueConstraint(condition=models.Q(('retired_at__isnull', True)), fields=('location', 'local_date'), name='chart_message_one_active_per_day')],
            },
        ),
    ]
