# Generated by Django 5.2.17 on 2026-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0005_chart_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmessage',
            name='unpinned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
