# Generated by Django 5.2.17 on 2026-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0006_chart_message_unpinned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'login_failure',
                'indexes': [models.Index(fields=['client_ip', 'failed_at'], name='login_failure_ip_at')],
            },
        ),
    ]
