# Generated by Django 5.2.17 on 2026-10-02 19:33
#
# Edited by hand (D-08, Phase 3 IN-02):
# - After the AddField, RunPython backfills every existing record's bot_key from its
#   location's current token. That is right because no token could change before Phase 4.
# - The hash is io_loop.bot_key (the first 12 hex digits of SHA-256 of the token), inlined:
#   a migration never imports app code. Only the hash is written; nothing is logged.
# - The column becomes NOT NULL in 0009, a separate migration, so no transaction both
#   updates rows and alters the table (RESEARCH A7).

import hashlib

from django.db import migrations, models


def backfill_bot_key(apps, schema_editor):
    Location = apps.get_model("powermon", "Location")
    ChartMessage = apps.get_model("powermon", "ChartMessage")
    # Every location, deleted ones too: every record needs a key before 0009.
    for location_id, token in Location.objects.values_list("id", "bot_token").iterator():
        ChartMessage.objects.filter(location_id=location_id, bot_key__isnull=True).update(
            bot_key=hashlib.sha256(token.encode()).hexdigest()[:12]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0007_login_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmessage',
            name='bot_key',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.RunPython(backfill_bot_key, migrations.RunPython.noop),
    ]
