# Generated by Django 5.2.17 on 2026-10-02 19:33
#
# No default on purpose: 0008 has filled bot_key on every existing record (D-08), and
# every new record is written with the posting bot's key (chart.lifecycle.INSERT_SQL).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0008_chart_message_bot_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartmessage',
            name='bot_key',
            field=models.CharField(max_length=12),
        ),
    ]
