# Generated by Django 5.2.17 on 2026-10-03 11:50
#
# No default and no backfill on purpose: NULL means "not reset", which is true of every
# existing record. A history reset (DATA-03, D-08) sets it on the location's active
# records, and the worker's chart lifecycle then releases them (chart.lifecycle.stale).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powermon', '0009_chart_message_bot_key_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmessage',
            name='history_reset_at',
            field=models.DateTimeField(null=True),
        ),
    ]
